-- Generado por Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   en:        2023-06-27 00:12:16 CLT
--   sitio:      Oracle Database 12cR2
--   tipo:      Oracle Database 12cR2



CREATE USER rayomcqueen IDENTIFIED BY ACCOUNT UNLOCK ;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE rayomcqueen.webtaller_categoria (
    nombre NVARCHAR2(45) NOT NULL,
    foto   NVARCHAR2(100)
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
NO INMEMORY;

ALTER TABLE rayomcqueen.webtaller_categoria
    ADD CONSTRAINT webtaller_categoria_pk PRIMARY KEY ( nombre )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );

CREATE TABLE rayomcqueen.webtaller_galeria (
    idgaleria     NUMBER(11)
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    foto          NVARCHAR2(100),
    reparacion_id NUMBER(11) NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
NO INMEMORY;

CREATE INDEX rayomcqueen.webtaller__reparacion_38b71975 ON
    rayomcqueen.webtaller_galeria (
        reparacion_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
        LOGGING;

ALTER TABLE rayomcqueen.webtaller_galeria
    ADD CONSTRAINT webtaller_galeria_pk PRIMARY KEY ( idgaleria )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT );

CREATE TABLE rayomcqueen.webtaller_reparacion (
    idreparacion NUMBER(11)
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    nombre       NVARCHAR2(45),
    descripcion  NCLOB,
    foto         NVARCHAR2(100),
    publicar     NUMBER(1) NOT NULL,
    comentario   NCLOB,
    categoria_id NVARCHAR2(45) NOT NULL,
    usuario_id   NUMBER(11) NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
NO INMEMORY
    LOB ( descripcion ) STORE AS SECUREFILE (
        TABLESPACE users
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    )
    LOB ( comentario ) STORE AS SECUREFILE (
        TABLESPACE users
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    );

ALTER TABLE rayomcqueen.webtaller_reparacion
    ADD CHECK ( "PUBLICAR" IN ( 0, 1 ) );

CREATE INDEX rayomcqueen.webtaller__categoria__a2b89db4 ON
    rayomcqueen.webtaller_reparacion (
        categoria_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

CREATE INDEX rayomcqueen.webtaller__usuario_id_e69c2152 ON
    rayomcqueen.webtaller_reparacion (
        usuario_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE rayomcqueen.webtaller_reparacion
    ADD CONSTRAINT webtaller_reparacion_pk PRIMARY KEY ( idreparacion )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );

CREATE TABLE rayomcqueen.webtaller_repuesto (
    idrepuesto   NUMBER(11)
        GENERATED BY DEFAULT ON NULL AS IDENTITY ( START WITH 1 CACHE 20 )
    NOT NULL,
    nombre       NVARCHAR2(45),
    precio       NUMBER(11) NOT NULL,
    descripcion  NCLOB,
    foto         NVARCHAR2(100),
    publicar     NUMBER(1) NOT NULL,
    comentario   NCLOB,
    categoria_id NVARCHAR2(45) NOT NULL,
    usuario_id   NUMBER(11) NOT NULL
)
PCTFREE 10 PCTUSED 40 TABLESPACE users LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT )
NO INMEMORY
    LOB ( descripcion ) STORE AS SECUREFILE (
        TABLESPACE users
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    )
    LOB ( comentario ) STORE AS SECUREFILE (
        TABLESPACE users
        STORAGE ( PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 BUFFER_POOL DEFAULT )
        CHUNK 8192
        RETENTION
        ENABLE STORAGE IN ROW
        NOCACHE LOGGING
    );

ALTER TABLE rayomcqueen.webtaller_repuesto
    ADD CHECK ( "PUBLICAR" IN ( 0, 1 ) );

CREATE INDEX rayomcqueen.webtaller__categoria__b166ff81 ON
    rayomcqueen.webtaller_repuesto (
        categoria_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

CREATE INDEX rayomcqueen.webtaller__usuario_id_71c68bc4 ON
    rayomcqueen.webtaller_repuesto (
        usuario_id
    ASC )
        TABLESPACE users PCTFREE 10
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT )
        LOGGING;

ALTER TABLE rayomcqueen.webtaller_repuesto
    ADD CONSTRAINT webtaller_repuesto_pk PRIMARY KEY ( idrepuesto )
        USING INDEX PCTFREE 10 INITRANS 2 TABLESPACE users LOGGING
            STORAGE ( INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT );

ALTER TABLE rayomcqueen.webtaller_reparacion
    ADD CONSTRAINT webtaller_categoria_a2b89db4_f FOREIGN KEY ( categoria_id )
        REFERENCES rayomcqueen.webtaller_categoria ( nombre )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE rayomcqueen.webtaller_repuesto
    ADD CONSTRAINT webtaller_categoria_b166ff81_f FOREIGN KEY ( categoria_id )
        REFERENCES rayomcqueen.webtaller_categoria ( nombre )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE rayomcqueen.webtaller_galeria
    ADD CONSTRAINT webtaller_reparacio_38b71975_f FOREIGN KEY ( reparacion_id )
        REFERENCES rayomcqueen.webtaller_reparacion ( idreparacion )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE rayomcqueen.webtaller_repuesto
    ADD CONSTRAINT webtaller_usuario_i_71c68bc4_f FOREIGN KEY ( usuario_id )
        REFERENCES rayomcqueen.auth_user ( id )
    DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE rayomcqueen.webtaller_reparacion
    ADD CONSTRAINT webtaller_usuario_i_e69c2152_f FOREIGN KEY ( usuario_id )
        REFERENCES rayomcqueen.auth_user ( id )
    DEFERRABLE INITIALLY DEFERRED;



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             5
-- ALTER TABLE                             11
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
