# Generated by Django 3.1.2 on 2023-06-27 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('idRepuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('precio', models.IntegerField(default=10)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(default='foto/default_repuesto.jpg', null=True, upload_to='foto')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='S/C')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webTaller.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('idReparacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(default='foto/default2.jpg', null=True, upload_to='foto')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='S/C')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webTaller.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idGaleria', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='foto')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webTaller.reparacion')),
            ],
        ),
    ]
