# Generated by Django 4.2.2 on 2023-07-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webTaller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
