# Generated by Django 4.2.2 on 2023-07-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webTaller', '0003_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='codigo',
        ),
    ]
